const products = [
  {
    name: "Apple iPhone 13",
    image: "./components/images/iphone13.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple iPhone 14",
    image: "./components/images/iphone14.png",
    category: "phone",
    description:
      "Революционные функции безопасности. Инновационная основная камера 48 Мп. Все это работает на новейшем чипе для смартфонов.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple iPhone 14 Pro Max",
    image: "./components/images/iphone14promax.png",
    category: "phone",
    description:
      "Революционные функции безопасности. Инновационная основная камера 48 Мп. Все это работает на новейшем чипе для смартфонов.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy A54",
    image: "./components/images/a54.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },

  {
    name: "Samsung Galaxy Z Flip4 5G",
    image: "./components/images/zFlip.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy S23 Ultra",
    image: "./components/images/S23Ultra.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR X8",
    image: "./components/images/honorx8.jpg",
    category: "phone",
    description: "",
    brand: "Honor",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR X9a",
    image: "./components/images/honorx9a.png",
    category: "phone",
    description:
      "HONOR X9a оснащен безрамочным OLED дисплеем 120 Гц с закругленными краями, Тройной камерой 64 Мп и оперативной памятью 6 Гб+5Гб HONOR RAM Turbo.",
    brand: "Honor",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR 70",
    image: "./components/images/honor70.jpg",
    category: "phone",
    description: "",
    brand: "Honor",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Redmi Note 12",
    image: "./components/images/redmi12.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi 12",
    image: "./components/images/xiaomi12.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi 13",
    image: "./components/images/xiaomi13.png",
    category: "phone",
    description: "The latest iPhone model with Face ID and edge-to-edge display.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple Watch Series 7",
    image: "./components/images/AppleWatchSeries7.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple Watch Series 8",
    image: "./components/images/AppleWatchSeries.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple Watch Ultra",
    image: "./components/images/AppleWatchUltra.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy Watch Active 2",
    image: "./components/images/SamsungGalaxyWatchActive2.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy Watch 4",
    image: "./components/images/SamsungGalaxyWatch4.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy Watch 5",
    image: "./components/images/SamsungGalaxyWatch5.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR Watch GS Pro",
    image: "./components/images/HONORWatchGSPro.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR MagicWatch 2",
    image: "./components/images/HONORMagicWatch2.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR Watch ES",
    image: "./components/images/HONORWatchES.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },

  {
    name: "Xiaomi Redmi Watch 2 Lite",
    image: "./components/images/XiaomiRedmiWatch2.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Mi Watch S1",
    image: "./components/images/XiaomiMiWatchS1.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Mi Watch S1 Pro GL",
    image: "./components/images/XiaomiMiWatchS1ProGL.png",
    category: "watch",
    description: "The latest Apple Watch with always-on display and built-in ECG.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple BYZ S852I",
    image: "./components/images/Apple_BYZ_S852I.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple AirPods Pro 2",
    image: "./components/images/AppleAirPodsPro2.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Apple AirPods Max",
    image: "./components/images/AppleAirPodsMax.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Apple",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung EO-IC100",
    image: "./components/images/Samsung_EO-IC100.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy Buds",
    image: "./components/images/SamsungGalaxyBudsSM-R170NZY.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "Samsung Galaxy Buds2 Pro",
    image: "./components/images/SamsungGalaxyBuds2Pro.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR Earbuds 2 Lite",
    image: "./components/images/HONOREarbuds2Lite.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR Choice EarBuds X3",
    image: "./components/images/HONORChoiceEarBudsX3.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "HONOR Choice EarBuds Lite",
    image: "./components/images/HONORChoiceEarBudsX3Lite.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Samsung",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Buds 3T Pro",
    image: "./components/images/XiaomiBuds3TPro.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Mi Earphones 2 Pro",
    image: "./components/images/XiaomiMiTrueWirelessEarphones2Pro.png",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
  {
    name: "Xiaomi Mi In-Ear Headphones",
    image: "./components/images/Xiaomi_Mi_In-Ear_Headphones.jpg",
    category: "headphones",
    description:
      "Wireless noise-cancelling headphones with up to 20 hours of battery life.",
    brand: "Xiaomi",
    dateAdded: "2023-05-25",
  },
];
